"use client";
import { Check, Copy, X } from "lucide-react";
import { useState } from "react";
import type { Claim } from "@/lib/types";
import { copyText } from "@/lib/utils";
import { ConfidenceBar } from "./confidence-bar";
import { EvidenceCard } from "./evidence-card";
import { VerdictBadge } from "./verdict-badge";
export function ClaimDetail({claim,onClose}:{claim:Claim;onClose:()=>void}){const[copied,setCopied]=useState(false);const copy=async()=>{await copyText(claim.text);setCopied(true);setTimeout(()=>setCopied(false),1200)};return <aside aria-label="Claim details" className="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto border-l border-border bg-card shadow-2xl transition sm:max-w-lg lg:sticky lg:top-6 lg:z-0 lg:max-h-[calc(100vh-3rem)] lg:w-auto lg:rounded-2xl lg:border"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-card/95 p-4 backdrop-blur"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Claim detail</p><div className="mt-2"><VerdictBadge verdict={claim.verdict}/></div></div><div className="flex gap-2"><button onClick={copy} className="button button-secondary size-9 p-0" aria-label="Copy claim">{copied?<Check className="size-4 text-success"/>:<Copy className="size-4"/>}</button><button onClick={onClose} className="button button-secondary size-9 p-0" aria-label="Close claim detail"><X className="size-4"/></button></div></div><div className="space-y-6 p-5"><section><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Claim text</p><p className="mt-2 text-base font-medium leading-7">“{claim.text}”</p></section><ConfidenceBar value={claim.confidence}/><section><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Explanation</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{claim.explanation}</p></section><section><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Evidence</p><span className="text-xs text-muted-foreground">{claim.evidence.length} source</span></div><div className="space-y-3">{claim.evidence.map(e=><EvidenceCard evidence={e} key={e.id}/>)}</div></section></div></aside>}

