"use client";
import { Check, Copy, FileText, Info } from "lucide-react";
import { useState } from "react";
import type { Claim, VerificationReport } from "@/lib/types";
import { copyText } from "@/lib/utils";
import { ClaimCard } from "./claim-card";
import { ClaimDetail } from "./claim-detail";
import { ReportSummary } from "./report-summary";
export function ReportWorkspace({report}:{report:VerificationReport}){const[selected,setSelected]=useState<Claim|null>(null);const[copied,setCopied]=useState(false);const copyReport=async()=>{const text=`TruthLens report — ${report.reliabilityScore}/100\n\n${report.claims.map(c=>`[${c.verdict.toUpperCase()}] ${c.text}`).join("\n")}`;await copyText(text);setCopied(true);setTimeout(()=>setCopied(false),1400)};return <><ReportSummary report={report}/><section className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_420px]"><div className="min-w-0 space-y-6"><div className="card p-5 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold"><FileText className="size-4 text-primary"/>Original AI response</div>{report.question&&<p className="mt-3 text-sm font-medium">Question: <span className="font-normal text-muted-foreground">{report.question}</span></p>}</div><button onClick={copyReport} className="button button-secondary h-9 shrink-0 px-3">{copied?<Check className="size-3.5 text-success"/>:<Copy className="size-3.5"/>}{copied?"Copied":"Copy report"}</button></div><p className="mt-4 text-sm leading-7 text-muted-foreground">{report.response}</p></div><div><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Verified claims</h2><p className="mt-1 text-sm text-muted-foreground">Select a claim to inspect its reasoning and evidence.</p></div><span title="Verdicts summarize the relationship between each claim and the available evidence."><Info className="size-4 text-muted-foreground"/></span></div><div className="space-y-3">{report.claims.map((claim,i)=><ClaimCard claim={claim} index={i} selected={selected?.id===claim.id} onSelect={()=>setSelected(claim)} key={claim.id}/>)}</div></div></div>{selected?<ClaimDetail claim={selected} onClose={()=>setSelected(null)}/>:<div className="sticky top-6 hidden h-[360px] place-items-center rounded-2xl border border-dashed border-border bg-card p-8 text-center lg:grid"><div><div className="mx-auto grid size-12 place-items-center rounded-full bg-muted"><FileText className="size-5 text-muted-foreground"/></div><p className="mt-4 text-sm font-semibold">Select a claim</p><p className="mt-2 max-w-xs text-sm leading-6 text-muted-foreground">Its verdict, explanation, confidence, and source evidence will appear here.</p></div></div>}</section>{selected&&<button aria-label="Close details" onClick={()=>setSelected(null)} className="fixed inset-0 z-40 bg-slate-950/35 lg:hidden"/>}</>}
